### ISSUE TITLE
"@type" parameter configuration in typed_config

### ISSUE THREAD

**Issue by iMaxGit** [cetanu/envoy_data_plane#24]
Hi @cetanu 

Thank you for making the envoy data plane functionality available in Python.
I am testing this approach to see if it is a viable alternative to writing a bootstrap configuration file for Envoy with Jinja2 templates, which can get a bit messy here.

I am not too familiar with protobuf, but I managed to create a yaml configuration file with some basic settings. However, I am not able to figure out how to create the `"@type"` parameter entry, as the type_config is Any type.

For example an entry like this:

```
    access_log:
    - name: envoy.access_loggers.file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
```

Would it be possible to share an example of how this would look in a Python program?

Thanks.
